apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metamorphosis
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - metamorphosis.example.com
      secretName: metamorphosis-tls
  rules:
    - host: metamorphosis.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metamorphosis
                port:
                  number: 80

